export const dogNames =[
    "Max", "Bella", "Charlie", "Lucy", "Buddy", "Daisy", "Rocky", "Molly", "Toby", "Sophie",
    "Jake", "Lola", "Cooper", "Sadie", "Bear", "Zoe", "Maggie", "Duke", "Chloe", "Riley",
    "Milo", "Coco", "Rex", "Luna", "Jack", "Gracie", "Oliver", "Abby", "Roxy", "Teddy",
    "Rufus", "Ruby", "Winston", "Nala", "Sasha", "Finn", "Mia", "Buster", "Rosie", "Oscar",
    "Penny", "Sam", "Zoey", "Dexter", "Ginger", "Hank", "Cali", "Tucker", "Ellie", "Louie",
    "Lily", "Bear", "Jax", "Holly", "Rusty", "Mabel", "Charlie", "Piper", "Maddie", "Kona",
    "Stella", "Otis", "Riley", "Jasmine", "Mia", "Murphy", "Misty", "Finn", "Sophie", "Maggie",
    "Apollo", "Tilly", "Lola", "Finn", "Dexter", "Maggie", "Oliver", "Zoey", "Toby", "Bailey",
    "Coco", "Roxy", "Leo", "Ella", "Juno", "Diesel", "Poppy", "Maya", "Nina", "Luna",
    "Chester", "Molly", "Max", "Rosie", "Ella", "Daisy", "Bailey", "Zeke", "Mia", "Baxter",
    "Scout", "Bliss", "Clyde", "Pearl", "Zara", "Jasper", "Harper", "Minnie", "Gus", "Athena",
    "Maddie", "Zeus", "Juno", "Koda", "Nina", "Benny", "Misty", "Sasha", "Ivy", "Rocky",
    "Angel", "Bandit", "Fiona", "Cleo", "Simba", "Chance", "Cinnamon", "Bruno", "Nala", "Daisy",
    "Ace", "Gracie", "Benny", "Freya", "Hunter", "Marley", "Misty", "Maggie", "Shadow", "Sandy",
    "Ella", "Thor", "Louie", "Willow", "Luna", "Buster", "Piper", "Lily", "Bailey", "Ginger",
    "Coco", "Monty", "Hazel", "Tucker", "Rosie", "Daisy", "Harley", "Finn", "Maggie", "Cleo",
    "Riley", "Rex", "Roxy", "Maya", "Buster", "Sophie", "Daisy", "Maggie", "Toby", "Ginger",
    "Zeus", "Nina", "Scout", "Lola", "Apollo", "Cali", "Riley", "Ruby", "Luna", "Oscar",
    "Lily", "Charlie", "Bear", "Rosie", "Fiona", "Gus", "Marley", "Maggie", "Finn", "Rex"
]